### ISSUE TITLE
Todo

### ISSUE THREAD

**Issue by djaiss** [monicahq/chandler#25]
Hard things remaining to do:

- [x] get rid of logs entirely. the system is clunky.
- [x] better newsfeed
- [x] notion of couple
- [x] notion of family
- [x] relationships
- [x] reminders by email and telegram

**Feature parity / services**

- [x] Manage account
- [x] Manage contact
- [X] Gender
- [x] Me as a contact
- [ ] Place
- [x] Pets 
- [x] Pronouns 
- [x] Labels 
- [x] Favorites
- [x] Navigate to labels
- [ ] Mark contact as deceased
- [x] Reminders
- [x] Address type (work, chalet, home, ...) 
- [x] Multiple addresses per contact 
- [x] Ways to contact (telephone, etc...) (contact fields and contact field types) 
- [x] Debts
- [x] Birthday
- [ ] How you met
- [x] Work information
- [ ] Export as vCard
- [x] Archive contact
- [x] Notes
    - [x] Dedicated page for notes
- [ ] Gifts
    - [x] Gift occasions
    - [x] Gift stages
- [x] Documents
- [x] Photos
- [x] Avatar
- [ ] Emotions
- [ ] Conversations
- [ ] Stay in touch
- [x] Calls audio/video
- [ ] Last called widget
- [ ] Activities
- [ ] Life events
- [ ] 2FA
- [x] Tasks

**New features**

- [ ] Reports
    - [ ] list of most/least contacted contacts
- [ ] ability to customize contact page
    - [ ] contact information
    - [x] all other data
    - [x] change template
- [x] Maiden name 
- [x] Audit logs 
- [x] Contact logs 
- [x] Group
    - [x] group details page
- [ ] communication (log email received)
- [x] Family summary module
- [x] Vault: give/change/remove permission to user  
- [x] Vault settings: 
    - [x] change default template
    - [x] delete vault
    - [x] manage users
- [ ] Journal
   - [x] list of journals
   - [x] edit/delete journal
   - [x] list of posts
   - [x] write/edit a post
   - [x] view post
   - [ ] search post content
   - [ ] search post title
   - [x] contacts in the post
   - [x] category
   - [X] time periods
- [ ] Goals
    - [x] list goals
    - [x] display goal details
    - [x] delete goal
    - [x] edit goal
- [x] Contact feed 
- [ ] indicate feelings between contacts (hate, love, etc...)
- [ ] instance administrator panel
- [x] religion
- [ ] race
- [ ] disability
- [x] 5 minutes journal (https://www.intelligentchange.com/products/the-five-minute-journal)
- [ ] daily planner
- [ ] weekly meal planner
- [x] mood tracker
- [ ] export templates as yml
- [ ] "on this week last year" reports
- [ ] send a report every sunday of what's coming next week

**out of scope for now**

- [ ] Try the product without signing up
- [ ] Weather
- [ ] Dark mode
- [ ] events

**Comment by djaiss** [comment]
![image](https://user-images.githubusercontent.com/61099/172899877-b076b654-f03c-45cc-b430-e490b55caaa6.png)

**Comment by njelich** [comment]
Might be a cool addition to the list:

- Mentions using something like https://github.com/zurb/tribute or a many-to-many connection for involved contacts in journal.

**Comment by njelich** [comment]
Another feature common in most similar apps but consistently not present in monica is contact enrichment. Grabbing info from FB, LinkedIn, Instagram etc could be really useful, especially for fields that take effort to keep up to date.

Maintaining it would definitely be more of a community effort thing, since these apps tend to change a bit over time.

**Comment by djaiss** [comment]
> Another feature common in most similar apps but consistently not present in monica is contact enrichment. Grabbing info from FB, LinkedIn, Instagram etc could be really useful, especially for fields that take effort to keep up to date.

This is something we haven't done yet even in the current Monica. It requires scraping their content which is somewhat not legal.

**Comment by njelich** [comment]
Actually, there are plenty of rulings at this point showing scrapping is [fully legal](https://medium.com/@tjwaterman99/web-scraping-is-now-legal-6bf0e5730a78). What I was thinking was a simple browser extension allowing you to quickly add a contact from a social network. This is not really data scrapping, just automation of normal user processes.

Some other questions would be about data migrations from monica to chandler, merging contacts and other ease-of-use improvements.

**Comment by KrGame** [comment]
Hello @djaiss , I don't know if this "indicate feelings between contacts (hate, love, etc...)" is also referencing to "mindmap" but if not can you consider adding it ? Now that you "redo" all the code.

**Comment by djaiss** [comment]
> Hello @djaiss , I don't know if this "indicate feelings between contacts (hate, love, etc...)" is also referencing to "mindmap" but if not can you consider adding it ? Now that you "redo" all the code.

Ok but what would mind maps do per se?

**Comment by KrGame** [comment]
> > Hello @djaiss , I don't know if this "indicate feelings between contacts (hate, love, etc...)" is also referencing to "mindmap" but if not can you consider adding it ? Now that you "redo" all the code.
> 
> Ok but what would mind maps do per se?

Well I have made a mindmap to see what it could look like here : https://github.com/monicahq/monica/issues/5530 
Depending on the person you choose to see the profile it can be the center person of the mindmap (Like I go on Person1 profile so he will be the center of the mindmap from my screenshot)

**Comment by Na0mir** [comment]
> Another feature common in most similar apps but consistently not present in monica is contact enrichment. Grabbing info from FB, LinkedIn, Instagram etc could be really useful, especially for fields that take effort to keep up to date.
> 
> Maintaining it would definitely be more of a community effort thing, since these apps tend to change a bit over time.

Hi everyone!
I personnaly believe this is the most important part, nowadays information is from everywhere with social networks and if you have 50+ contacts close to you it's almost impossible to be up to date compared to Linkedin/Facebook/Instagram/Others networks.

Even with limited data grabbing such as profile picture, current job and current city/country (already public ?) this would be already amazing!
